manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: Cris1Z
      url-base: https://github.com/Cris1Z/
    - name: halfdane
      url-base: https://github.com/halfdane/
    - name: oleksandrmaslov
      url-base: https://github.com/oleksandrmaslov/
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
      
    - name: zmk-input-gestures
      remote: Cris1Z
      revision: main

    # Add these if you want to use absolute mode:
    - name: zmk-input-processors
      remote: halfdane
      revision: main

    - name: cirque-input-module
      remote: Cris1Z
      revision: absolute_mode
  self:
    path: config
